### PR TITLE
Feature Updates for PSM

### PR DESCRIPTION
**Pull request by OSXLich-Doug**
Updates Infomon to handle PSM abilities

Breaks out CMan and adds Feat, Weapon, Armor and Shield to ./lib structure

Adds .affordable? and .known? functions for abilities

Requires rigorous testing.

### CODE REVIEW

**Comment by wmahmoud** [comment]
Need to add check in `lich.rbw` to ignore `spell-list.xml` entries for Combat Maneuvers.  Currently can cause issues when CMs are defined in the spell-list.xml, and the full name is sent to `def_ CMan.[](name)` or `CMan.[]=(name,val)` in the form of a nebulous error to the user.

If we send a sanitized `spell-list.xml`, it would solve the issue but annihilate existing custom spell preps.

**Comment by OSXLich-Doug** [comment]
Added CMan.available?(:ability) and Weapon.available?(:ability) to undo spell-list challenges.  

spell-list remains unchanged this iteration - there are probably too many scripts out there relying on it, so we'll start with just CMan (everything else is net new, and isn't present anyway unless someone's going nuts over 10 second cooldown captures).

In lich.rbw removed the 'known?' scan of spell-list at spell circle 96 (cmans).  Hard deprecation. It will serve as the first warning that spell-list is going to lose CMans.

**Comment by OSXLich-Doug** [comment]
Error in Feat class - correct downcasee to downcase

**Comment by lorddemandred** [comment]
So I've been running on this for a few days now, and am up to date. Looking real good so far! I do notice that, whether it's me redesigning around these changes, or if it's the changes themselves, but my *little* attack scripts, that just do one action and then stop, are a lot quicker now. They used to tend to . . . drag? . . . a little. If it's these changes that's responsible, let's hear it for changes!

Demandred('s player)

**Pull request merged**
